{% set name = "google-api-core" %}
{% set version = "2.30.0" %}

package:
  name: {{ name|lower }}-split
  version: {{ version }}

source:
  url: https://pypi.org/packages/source/{{ name[0] }}/{{ name }}/{{ name.replace('-', '_') }}-{{ version }}.tar.gz
  sha256: 02edfa9fab31e17fc0befb5f161b3bf93c9096d99aed584625f38065c511ad9b

build:
  number: 0
  noarch: python

outputs:
  - name: {{ name }}
    build:
      noarch: python
      script: python -m pip install . -vv --no-deps --no-build-isolation
    requirements:
      host:
        - python {{ python_min }}
        - pip
        - setuptools
      run:
        - python >={{ python_min }}
        - googleapis-common-protos >=1.56.2,<2.0.0
        - protobuf >=3.19.5,<7.0.0,!=3.20.0,!=3.20.1,!=4.21.0,!=4.21.1,!=4.21.2,!=4.21.3,!=4.21.4,!=4.21.5
        # use the most restrictive constraints (for python >=3.13) to remain noarch: python
        - proto-plus >=1.25.0,<2.0.0
        - google-auth >=2.14.1,<3.0.0
        - requests >=2.18.0,<3.0.0
    test:
      requires:
        - pip
        - python {{ python_min }}
      imports:
        - google.auth
        - google.auth.credentials
        - google.auth.transport.requests
        - google.longrunning
        - google.longrunning.operations_pb2
        - google.protobuf
        - google.rpc
        - google.api_core
        - google.api_core.exceptions
        - google.api_core.future
        - google.api_core.future.base
        - google.api_core.future.polling
        - google.api_core.general_helpers
        - google.api_core.page_iterator
        - google.api_core.protobuf_helpers
        - google.api_core.retry
        - google.api_core.timeout
      commands:
        - python -m pip check

  - name: {{ name }}-grpc
    build:
      # noarch: python rather than noarch: generic because different python constraints
      noarch: python
    requirements:
      host:
        - python {{ python_min }}
      run:
        # excluding python 3.14 for now because we don't have the required grpcio on conda-forge
        - python >={{ python_min }},<3.14
        - {{ pin_subpackage(name, exact=True) }}
        # upstream has tightest bounds for python >=3.14 but we can't yet support these, so we
        # adopt python >=3.11 constraints for all python versions to avoid giving up noarch builds
        - grpcio >=1.49.1,<2.0.0
        - grpcio-status >=1.49.1,<2.0.0
    test:
      requires:
        - python {{ python_min }}
        - pip
      imports:
        - google.api_core
      commands:
        - python -m pip check
    about:
      home: https://github.com/googleapis/python-api-core
      license: Apache-2.0
      license_family: APACHE
      summary: Core Library for Google Client Libraries with grpc

about:
  home: https://github.com/googleapis/python-api-core
  license: Apache-2.0
  license_family: APACHE
  license_file: LICENSE
  summary: Core Library for Google Client Libraries
  description: |
    Core Library for Google Client Libraries
    -------------------------

    This package does not include the grpc, grpcio-gcp or grpcgcp extra requirements.

    This library is not meant to stand-alone. Instead it defines
    common helpers used by all Google API clients. For more information, see the
    [documentation](https://googleapis.dev/python/google-api-core/latest/index.html).

    Supported Python Versions
    -------------------------
    Python >= 3.5

    Deprecated Python Versions
    --------------------------
    Python == 2.7
    - Python 2.7 support will be removed on January 1, 2020.
    - protobuf does not support Visual C++ 2008, windows py27 package not available

  doc_url: https://googleapis.dev/python/google-api-core/latest/index.html
  dev_url: https://github.com/googleapis/python-api-core

extra:
  feedstock-name: google-api-core
  recipe-maintainers:
    - xylar
    - BrentDorsey
    - parthea
    - tpdownes
    - tswast
