{% set name = "google-api-core" %}
{% set version = "1.8.1" %}
{% set sha256 = "25e20c24395439dffcdb6e364cc6adb9b28a9e28d516ef5a51b9266ae0894a44" %}
{% set build = 0 %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  fn: {{ name }}-{{ version }}.tar.gz
  url: https://pypi.org/packages/source/{{ name[0] }}/{{ name }}/{{ name }}-{{ version }}.tar.gz
  sha256: {{ sha256 }}

build:
  number: 0
  script: python -m pip install --no-deps --ignore-installed .

requirements:
  build:
    - python
    - setuptools
    - pip

  run:
    - python
    - googleapis-common-protos >=1.5.3,<2.0dev
    - protobuf >=3.4.0
    - google-auth >=0.4.0,<2.0.0dev
    - requests >=2.18.0,<3.0.0dev
    - setuptools >=34.0.0
    - six >=1.10.0
    - pytz
    # Backport of concurrent.futures for Python < 3.2.
    - futures >=3.0.0  # [py2k]

test:
  imports:
    - google.api_core.exceptions

about:
  home: https://github.com/GoogleCloudPlatform/google-cloud-python/tree/master/core
  license: Apache-2.0
  license_family: Apache
  license_file: LICENSE
  summary: 'Core Library for Google Client Libraries'
  description: This library is not meant to stand-alone. Instead it defines
    common helpers used by all Google API clients.
  doc_url: https://googlecloudplatform.github.io/google-cloud-python/latest/core/
  dev_url: https://github.com/GoogleCloudPlatform/google-cloud-python/tree/master/api_core

extra:
  recipe-maintainers:
    - parthea
    - tswast
