schema_version: 1

context:
  name: google-api-core
  version: 2.30.0

recipe:
  name: ${{ name|lower }}-split
  version: ${{ version }}

source:
  url: https://pypi.org/packages/source/${{ name[0] }}/${{ name }}/${{ name|replace('-', '_') }}-${{ version }}.tar.gz
  sha256: 02edfa9fab31e17fc0befb5f161b3bf93c9096d99aed584625f38065c511ad9b

build:
  number: 0

outputs:
  - package:
      name: ${{ name }}
    build:
      noarch: python
      script: ${{ PYTHON }} -m pip install . -vv --no-deps --no-build-isolation
    requirements:
      host:
        - python ${{ python_min }}.*
        - pip
        - setuptools
      run:
        - python >=${{ python_min }}
        - googleapis-common-protos >=1.56.3,<2.0.0
        - protobuf >=4.25.8,<7.0.0
        # use the most restrictive constraints (for python >=3.13) to remain noarch: python
        - proto-plus >=1.25.0,<2.0.0
        - google-auth >=2.14.1,<3.0.0
        - requests >=2.20.0,<3.0.0
    tests:
      - python:
          imports:
            - google.auth
            - google.auth.credentials
            - google.auth.transport.requests
            - google.longrunning
            - google.longrunning.operations_pb2
            - google.protobuf
            - google.rpc
            - google.api_core
            - google.api_core.exceptions
            - google.api_core.future
            - google.api_core.future.base
            - google.api_core.future.polling
            - google.api_core.general_helpers
            - google.api_core.page_iterator
            - google.api_core.protobuf_helpers
            - google.api_core.retry
            - google.api_core.timeout
          python_version: ${{ python_min }}.*
          pip_check: true

  - package:
      name: ${{ name }}-grpc
    build:
      # noarch: python rather than noarch: generic because different python constraints
      noarch: python
    requirements:
      host:
        - python ${{ python_min }}.*
      run:
        - python >=${{ python_min }}
        - ${{ pin_subpackage(name, exact=true) }}
        # using the tightest constraints for python >= 3.14
        - grpcio >=1.75.1,<2.0.0
        - grpcio-status >=1.75.1,<2.0.0
    tests:
      - python:
          imports:
            - google.api_core
          python_version: ${{ python_min }}.*
          pip_check: true

about:
  homepage: https://github.com/googleapis/google-cloud-python/tree/main/packages/google-api-core
  license: Apache-2.0
  license_family: APACHE
  license_file: LICENSE
  summary: Google API client core library
  description: |
    Google API client core library
    -------------------------

    This library is not meant to stand-alone. Instead it defines
    common helpers used by all Google API clients. For more information, see the
    [documentation](https://googleapis.dev/python/google-api-core/latest).

  documentation: https://googleapis.dev/python/google-api-core/latest/index.html
  repository: https://github.com/googleapis/google-cloud-python/tree/main/packages/google-api-core

extra:
  feedstock-name: google-api-core
  recipe-maintainers:
    - xylar
    - BrentDorsey
    - parthea
    - tpdownes
    - tswast
